# Generated by Django 3.1.3 on 2020-12-31 06:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfPhases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default=0, max_length=100)),
                ('description', models.TextField(default=0)),
                ('timeline', models.CharField(default=0, max_length=100)),
                ('payments', models.IntegerField(default=0)),
                ('macth', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.vendor'),
        ),
        migrations.AddField(
            model_name='client',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('client', 'vendor')},
        ),
    ]
